name: Improvement
description: Suggest an improvement or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What would you like to improve and why?
